"""
Django settings for myWebsite project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(072&f%b@^^6zu#y7d3vl57y+f#ja^jmc_bb!rq(g)no)91#3='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'appWeb.apps.AppwebConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myWebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'dbSQLiteWeb'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# de su dung authen cua abstract user thi can phai cau hinh AUTH_USER_MODEL = ten app chua model user ma ta tao roi . roi ten user ma ta tao trong models.py
# dung python manage.py makemigrations va python manage.py migrate de tao csdl moi
# neu viec tao csdl nay ko phai la makemigrations va migrate lan dau thi can phai xoa file csdl cu
# va xoa toan bo file makemigrations trong thu muc migrations de user model (duoc tham chieu boi AUTH_USER_MODEL) ma ta tao se duoc tao ra trong migration dau tien cua app (chinh la file 0001_initial.py)
AUTH_USER_MODEL = 'appWeb.MyUser'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# nhung cai nay phuc vu cho viec tuy chinh giao dien admin

# STATIC_ROOT dung cho viec chi dinh ten thu muc chua tat ca cac file static cua cac app
# chay cau lenh python manage.py collectstatic tren terminal tai thu muc cung cap manage.py de lay cac file static cau hinh giao dien admin
#STATIC_ROOT = 'static'

# hinh nhu co cai STATICFILES_DIRS roi thi ko can STATIC_ROOT nua
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'ten thu muc trong STATIC_ROOT')
    os.path.join(BASE_DIR, 'static'),
]

# sau khi chinh sua giao dien theo y minh muon, an ctrl + f5 tai giao dien admin de cap nhat lai giao dien

# de thay doi html cua admin, vi du la giao dien log in
# tim den file login.html trong https://github.com/django/django/tree/main/django/contrib/admin/templates/admin, copy noi dung file
# roi tao thu muc admin trong thu muc duoc chi dinh tai TEMPLATES, tao file login.html, paste du lieu file login.html
# roi thay doi theo y minh muon
